application: stq-dev
version: alpha
runtime: python27
api_version: 1
threadsafe: True


handlers:
- url: /static/stylesheets/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: /static/javascripts/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /.*
  script: main.app

builtins:
- remote_api: on
- deferred: on

libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
